title: Real Estate Investment Trust - REIT Yer
logo: /assets/img/real asset token.png
description: Real Estate Investment Trust-REIR YER.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
